### ISSUE TITLE
exit_code not defined

### ISSUE THREAD

**Issue by magau** [selivan/zabbix-import#3]
Hi Selivanov,
First of all let me tell you that you've done a good job!
So, I don't know why but I'm getting an error related with the exit_code variable:

```
$ ./zbx-import.py --help
usage: zbx-import.py [-h] -u USER -p PASSWORD [-s URL] template_file

Import XML configuration files using Zabbix API

positional arguments:
  template_file

optional arguments:
  -h, --help            show this help message and exit
  -u USER, --user USER  user name
  -p PASSWORD, --password PASSWORD, --pass PASSWORD
                        password
  -s URL, --url URL     Zabbix API URL, default is
                        http://127.0.0.1:80/api_jsonrpc.php
Traceback (most recent call last):
  File "./zbx-import.py", line 37, in <module>
    args = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1034, in __call__
    parser.exit()
  File "/usr/lib/python3.6/argparse.py", line 2389, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zbx-import.py", line 100, in <module>
    sys.exit(exit_code)
NameError: name 'exit_code' is not defined
```

**Comment by magau** [comment]
The solution that I've found was simply moving the _exit_code_ variable assignement to the beginning of the _try_ statement...
It works like a charm! Thanks, once again!

By the way, I've also noticed that for updating already existing triggers, with a new expression, creates a new trigger with the same name and keeps the old one (with the old expression)...

I know that this is out of the scope and if it is a bug it sure relies on zabbix it self, but have you faced something similar?

I have to add the `'deleteMissing': True` for the trigger update to work...

**Comment by selivan** [comment]
Hi @magau 

Thanks for the bug report.

Fixed error with `exit_code`, argument parsing should not be inside `try` case. Also moved exit_code=1 on top of code block as you suggested. Commit e6856c78f4891ab806d22c63101cb6022796c378

About `deleteMissing`: both Zabbix web interface and API by default set this option to False. I don't want to override defaults. So I created a new option `--delete-missing=yes|no(default)` that allows to set it explicitly. Also I added options for other possible parameters: `--create-missing=yes(default)|no` and `--update-existing=yes(default)|no`. Now this tool has all options available from import web interface. Commit 8d5ff0684a3845a48dcc663be588f3bebbde8fc2

Thanks again for the report and suggestions. It's nice to know that your work is useful :)

**Comment by magau** [comment]
I guess you've forgot to remove a system exit right after printing the parsed args...
https://github.com/selivan/zabbix-import/blob/master/zbx-import.py#L54
Thanks man!

**Comment by selivan** [comment]
Ups, forgot to remove debug stub. Good catch!

**Comment by magau** [comment]
Just one more last thing... ;)
Change the _--create-new_ argument to _--create-missing_ (https://github.com/selivan/zabbix-import/blob/master/zbx-import.py#L45)

**Comment by selivan** [comment]
Zabbix web interface calls this option "Create new": https://www.zabbix.com/documentation/3.4/manual/xml_export_import/templates#importing, and API calls it "createMissing". I think more people are using web interface than API, so I chose web interface naming.
